### PR TITLE
fix sample load infinite loop

### PR DESCRIPTION
**Pull request by anwilkie**
# What and why?
This PR is an attempt at fixing a bug where r-ops hangs when attempting to load a sample file with a duplicated sample unit. The code has changed so that an error message box appears on the page to indicate that there's a problem with the file.

# How to test?
* Create a sample file that has a duplicate sample unit ref.
* Deploy this PR to your environment and run acceptance tests.
* Create a collection exercise and attach the aforementioned sample file to the CE.
* Keep refreshing the page to check the sample file load process. At first, it will look like it's hanging, but after a while, it will eventually display an "error loading sample" box on the page.
* Check the logs for the sample service pod. There should be some stuff about the sample summary getting set to failed (which didn't happen before).

# Trello
[Card](https://trello.com/c/upvtJmqp)

### CODE REVIEW

**Comment by anwilkie** [comment]
I changed the response from a 409 conflict to a 422 unprocessible entity. For some reason, this makes the infinite loop abort and display an error message, and kick of the dead letter stuff, with the sample summary getting set to false. But, you're right that I forgot to update the openapi.yaml. I'll do that.

**Review by arroyoAle — APPROVED** [review]

**Review by insacuri — CHANGES_REQUESTED** [review]
Before this goes in.  Can you figure out why we made it a 405 to begin with?  I'm pretty sure there was a legit reason for it but I can't remember what, and I'm uncomfortable changing it by saying 'oh it seems to work' without fully understanding it

**Comment by anwilkie** [comment]
This bug has been fixed as part of another PR, so I'm closing this.

**Pull request closed without merging**
