### PR TITLE
Make pgcrypto extension installation consistent with the Action service

### PR DESCRIPTION
**Pull request by johntopleyons**
# Motivation and Context
Whilst porting RM to Kubernetes running on Google Kubernetes Engine (GKE), I ran into problems with the database migrations and the installation of the **pgcrypto** PostgreSQL extension. Both the Action and Sample services use this extension and contain database migrations to install it. The problem is that as each service currently tries to install the extension in its own service schema it isn't accessible from the other service. The correct solution is to install the extension in the **public** schema, which is accessible everywhere by default.

Additionally the way the Sample service installs the extension isn't consistent with the way the Action service installs it. The Action service contains code to install the extension in various other database scripts.

# What has changed
* Create the extension in **schema.sql** (explicitly specifying the `public` schema) before setting the search path
* Create the extension in **schema-cloud.sql** to be consistent with the Action service
* Create the extension in **groundzero.sql** to be consistent with the Action service
* Explicitly specify the `public` schema in the extension creation statement in **sample_add_uuids.sql**

# How to test?
I created new Action and Sample service Docker images tagged _census_ and was able to test them successfully creating new pods in GKE. I have **not** tested on Cloud Foundry, nor have I tested what happens if the extension is already installed in the Action or Sample service schemas. To do so would have been far beyond my scope of getting RM working from scratch on Kubernetes.

# Links
N/A

### CODE REVIEW

**Comment by NickGrantONS** [comment]
We are thinking about closing this PR, because it's quite old and the Travis build was problematic when this was tried in its partner PR. Can we either get it working or close it?

**Comment by johntopleyons** [comment]
Are you planning on addressing the problem, or does it just go away anyway because there isn't a Sample service for census?

**Comment by NickGrantONS** [comment]
I guess we should bite the bullet, so we have the option to use GC as well as AWS. What do you think @davidmort ?

**Comment by AndrewTorrance** [comment]
I'm not sure if this is ready to be approved. Doesnt the 'how to test' section comments mean we have to test this out more thoroughly first ?

**Comment by owencjones** [comment]
The thing that stops me approving this is this bit:
> I have **not** tested on Cloud Foundry
We need a strategy for how we can as team work out how we'll handle this.  I think @johntopleyons says fairly that it's out of his scope, but we should maybe block this with a task to test it on CF for a team whose scope it is within.

**Comment by NickGrantONS** [comment]
Closing this PR but keeping the branch. Have created a new Trello card to look at this again when we have time: https://trello.com/c/qDqT4SQ9/747-sample-service-future-proof-for-kubernates-google-cloud

**Pull request closed without merging**
